[package]
name = "fast_woothee"
version = "1.0.0"
authors = ["Ian Ker-Seymer <i.kerseymer@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
woothee = "^0.6"
ruru = "*"


[package.metadata.thermite]
github_releases = true
github_release_type = "latest"
